########################################################
########### ONLINE RETAIL STORE API TEST ###############
########################################################

@host = localhost
@port = 8082
@url = http://{{host}}:{{port}}
@token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXRpbjIzQGdqLmNvbSIsImlhdCI6MTczMjI2NTI5Nn0.z0aIExksEARehCQH9bEPAbByLCzJn9o95PZn7f_aZ4c

########################################################
########### ADD NEW CUSTOMER ENDPOINT ##################
########################################################
POST {{url}}/api/addCustomer

{
    "customerName": "Jatin Kumar",
    "customerEmail": "jatin@123",
    "customerBillingAddress": {
	"doorNo": "213",
	"streetName": "Koramangala",
	"layout": "HSR Layout",
	"city": "Bangalore",
	"pincode": "560102"
    },
    "customerShippingAddress": {
	"doorNo": "213",
	"streetName": "Koramangala",
	"layout": "HSR Layout",
	"city": "Bangalore",
	"pincode": "560102"
    }
}

########################################################
########### SEARCH CUSTOMER ENDPOINT ###################
########################################################
GET {{url}}/api/searchCustomer?customerId=1


########################################################
########### DELETE CUSTOMER ENDPOINT ###################
########################################################
DELETE {{url}}/api/deleteCustomer/1


########################################################
########### UPDATE CUSTOMER ENDPOINT ###################
########################################################
PUT {{url}}/api/updateCustomer

{
    "id": 1,
    "customerName": "JatiN Kumar",
    "customerEmail": "jatin@123"
}
