########################################################
########### ONLINE RETAIL STORE API TEST ###############
########################################################

@host = localhost
@port = 8082
@url = http://{{host}}:{{port}}
@token=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYXRpbjIzQGdqLmNvbSIsImlhdCI6MTczMjI2NTI5Nn0.z0aIExksEARehCQH9bEPAbByLCzJn9o95PZn7f_aZ4c

########################################################
########### ADD NEW CUSTOMER ENDPOINT ##################
########################################################
POST {{url}}/api/addCustomer

{
    "customerName": "Jatin Kumar",
    "customerEmail": "jatin@123",
    "customerBillingAddress": {
	"doorNo": "213",
	"streetName": "Koramangala",
	"layout": "HSR Layout",
	"city": "Bangalore",
	"pincode": "560102"
    },
    "customerShippingAddress": {
	"doorNo": "213",
	"streetName": "Koramangala",
	"layout": "HSR Layout",
	"city": "Bangalore",
	"pincode": "560102"
    }
}

########################################################
########### SEARCH CUSTOMER ENDPOINT ###################
########################################################
GET {{url}}/api/searchCustomer?customerId=1


########################################################
########### DELETE CUSTOMER ENDPOINT ###################
########################################################
DELETE {{url}}/api/deleteCustomer/1


########################################################
########### UPDATE CUSTOMER ENDPOINT ###################
########################################################
PUT {{url}}/api/updateCustomer

{
    "id": 1,
    "customerName": "JatiN Kumar",
    "customerEmail": "jatin@123"
}

########################################################
########### SHOPPING SERVICE ENDPOINTS #################
########################################################
@port=8087
@url=http://{{host}}:{{port}}/api/shopping-service

@customerId=1

### GET CUSTOMER DETAILS    
GET {{url}}/customer/{{customerId}}

### GET CUSTOMER CART
GET {{url}}/customer/{{customerId}}/cart

### UPDATE CUSTOMER CART 
PUT {{url}}/customer/{{customerId}}/cart

{
	"cartId": 1,
	"lineItems": {
	    "itemId": 1,
	    "productId": 1,
	    "productName": "Laptop",
	    "quantity": 1,
	    "price": 50000
	}
}

### ADD PRODUCT TO INVENTORY
POST {{url}}/products

{
    "productName": "Laptop",
    "productDescription": "Dell Inspiron 15",
    "quantity": 10,
    "price": 50000	
}

### GET ALL ORDERS
GET {{url}}/customer/{{customerId}}/orders

### PLACE ORDER
POST {{url}}/customer/{{customerId}}/orders
