server:
  port: 8080
management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway
spring:
  application.name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery.locator.enabled: true
      routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/products/**
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates: Path=/customers/**
        - id: order-service
          uri: lb://ORDERS-SERVICE
          predicates: Path=/orders/**
        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates: Path=/inventory/**
